### ISSUE TITLE
Unhandled exception whilist trying to connect to the server.

### ISSUE THREAD

**Issue by MiamiCenterPL** [SlejmUr/PayCheck3#34]
This is my console log:

Starting Server(s)!
[INFO] Update Finished!
HTTPS Server started!
Enter q to quit.
something isnt good
Unhandled exception. System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.FormatException: The input is not a valid Base-64 string as it contains a non-base 64 character, more than two padding characters, or an illegal character among the padding characters.
   at System.Convert.FromBase64CharPtr(Char* inputPtr, Int32 inputLength)
   at System.Convert.FromBase64String(String s)
   at PayCheckServerLib.TokenHelper.ReadToken(String base64) in D:\a\PayCheck3\PayCheck3\PayCheckServerLib\Helpers\TokenHelper.cs:line 112
   at PayCheckServerLib.WSController.LobbyControl.Lobby(WebSocketStruct socketStruct) in D:\a\PayCheck3\PayCheck3\PayCheckServerLib\WSController\LobbyControl.cs:line 32
   at InvokeStub_LobbyControl.Lobby(Object, Object, IntPtr*)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at ModdableWebServer.Helper.RequestSender.SendRequestWS(WebSocketStruct wsStruct, Dictionary`2 wsMethods)
   at ModdableWebServer.Servers.WSS_Server.Session.OnWsDisconnected()
   at NetCoreServer.WssSession.OnDisconnected()
   at NetCoreServer.SslSession.Disconnect()
   at NetCoreServer.SslSession.ProcessReceive(IAsyncResult result)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.AwaitTaskContinuation.RunCallback(ContextCallback callback, Object state, Task& currentTask)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
   
   I am using the latest version of PC3. It's probably due to the last update.

**Comment by SlejmUr** [comment]
You need to start server then start pd3, it seems somehow cant get the token or you already have it. Which means you connected to their server before connecting to your server

**Comment by MiamiCenterPL** [comment]
Upon trying it - I get this log-in panel, but I can't really log-in (and I did passed in a correct password)
![image](https://github.com/SlejmUr/PayCheck3/assets/19477010/49fc81e7-cacc-4147-8503-b59932438737)

**Comment by SlejmUr** [comment]
Which platform are you using?

**Comment by MiamiCenterPL** [comment]
Steam

**Comment by MiamiCenterPL** [comment]
Is this issue casued by my setup (config or smthng) or server emulator broke after the update?

**Comment by SlejmUr** [comment]
Ohhhh the game had an update :DD okay that means it broke it

**Comment by HW12Dev** [comment]
Should be fixed in the latest commit https://github.com/SlejmUr/PayCheck3/commit/9100252121b4de0e58a9d1450796b2c1fc542b70
